version: '3.9'
services:
  frontend:
    container_name: shopper_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      - backend

  backend:
    container_name: shopper_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=shopper_db
      - HOSTNAME=db
      - PORT=3001
  
  db_mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - 3306:3306
    platform: linux/x86_64
    restart: 'always'
    environment:
      - MYSQL_ROOT_PASSWORD=password

  networks:
    default:
      name: shopper_api_net
